version: '3.7'

services:
  web:
    image: markoshust/magento-php:8.1-fpm
    container_name: magento-web
    volumes:
      - ./html:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: magento-nginx
    volumes:
      - ./html:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "${MAGENTO_PORT}:80"
    depends_on:
      - web

  db:
    image: mysql:5.7
    container_name: magento-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
